// apps/frontend-nuxtjs/pages/login.vue
<template>
  <div class="min-h-screen flex flex-col">
    <TopBar />

    <main class="flex-1 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8 bg-surface-secondary">
      <div class="max-w-md w-full">
        <div class="bg-surface-primary rounded-lg shadow-lg p-8">
          <div class="text-center mb-8">
            <h2 class="text-3xl font-bold text-foreground">Sign In</h2>
            <p class="mt-2 text-sm text-muted">
              Don't have an account?
              <NuxtLink to="/register" class="text-primary-600 hover:text-primary-700 font-medium">
                Sign up
              </NuxtLink>
            </p>
          </div>

          <form @submit.prevent="handleLogin" class="space-y-6">
            <Input
              id="email"
              v-model="form.email"
              type="email"
              label="Email"
              placeholder="you@example.com"
              required
              :error="errors.email"
            />

            <Input
              id="password"
              v-model="form.password"
              type="password"
              label="Password"
              placeholder="••••••••"
              required
              :error="errors.password"
            />

            <div class="flex items-center justify-between text-sm">
              <div class="flex items-center">
                <input
                  id="remember-me"
                  v-model="form.rememberMe"
                  type="checkbox"
                  class="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded"
                />
                <label for="remember-me" class="ml-2 block text-muted">
                  Remember me
                </label>
              </div>

              <NuxtLink to="/forgot-password" class="text-primary-600 hover:text-primary-700">
                Forgot password?
              </NuxtLink>
            </div>

            <Button
              type="submit"
              class="w-full"
              :loading="loading"
              :disabled="loading"
            >
              Sign In
            </Button>
          </form>

          <!-- Demo Users Info -->
          <div v-if="demoUsers.length > 0" class="mt-6 pt-6 border-t border-border">
            <p class="text-sm text-muted text-center mb-3">Demo accounts (for testing):</p>
            <div class="space-y-2">
              <button
                v-for="user in demoUsers"
                :key="user.email"
                @click="fillDemoCredentials(user.email)"
                class="w-full text-left px-3 py-2 text-sm bg-surface-secondary hover:bg-gray-100 dark:hover:bg-gray-700 rounded transition-colors"
              >
                <span class="font-medium text-foreground">{{ user.email }}</span>
                <span class="text-muted ml-2">({{ user.role }})</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </main>

    <Footer />
  </div>
</template>

<script setup lang="ts">
const { login } = useAuth();
const toast = useToast();
const router = useRouter();
const route = useRoute();
const config = useRuntimeConfig();

const form = reactive({
  email: '',
  password: '',
  rememberMe: true,
});

const errors = reactive({
  email: '',
  password: '',
});

const loading = ref(false);

// Parse demo users from config
const demoUsers = computed(() => {
  const domain = config.public.demoDomain;
  const users = config.public.demoUsers;

  if (!domain || !users) return [];

  return users.split(',').map((user: string) => {
    const role = user.includes('admin') ? (user.includes('sys') ? 'sysadmin' : 'admin') : 'guest';
    return {
      email: `${user}@${domain}`,
      role,
    };
  });
});

const fillDemoCredentials = (email: string) => {
  form.email = email;
  form.password = config.public.demoPassword || '';
};

const validateForm = () => {
  errors.email = '';
  errors.password = '';

  if (!form.email) {
    errors.email = 'Email is required';
    return false;
  }

  if (!isValidEmail(form.email)) {
    errors.email = 'Invalid email format';
    return false;
  }

  if (!form.password) {
    errors.password = 'Password is required';
    return false;
  }

  return true;
};

const handleLogin = async () => {
  if (!validateForm()) return;

  loading.value = true;

  try {
    const response = await login({
      email: form.email,
      password: form.password,
    });

    // Check if email is verified
    if (response.user && !response.user.emailVerified) {
      toast.warning('Please verify your email address to continue. Check your inbox.');
      // Still allow login but show warning
    }

    toast.success('Login successful!');

    // Redirect to intended page or dashboard
    const redirect = route.query.redirect as string;
    await router.push(redirect || '/dashboard/todos');
  } catch (error: any) {
    console.error('Login error:', error);

    if (error.message?.includes('email') && error.message?.includes('verified')) {
      toast.error('Please verify your email address before logging in.');
    } else if (error.message?.includes('credentials') || error.message?.includes('Invalid')) {
      toast.error('Invalid email or password');
    } else {
      toast.error(error.message || 'Login failed. Please try again.');
    }
  } finally {
    loading.value = false;
  }
};

definePageMeta({
  middleware: 'guest',
});
</script>

// apps/frontend-nextjs/src/app/login/page.tsx
"use client";

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useAuthStore } from '@/lib/store';

export default function LoginPage() {
  const router = useRouter();
  const { login, isLoading } = useAuthStore();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [rememberMe, setRememberMe] = useState(true);
  const [error, setError] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    try {
      await login(email, password, rememberMe);
      router.push('/dashboard/todos');
    } catch (err: any) {
      setError(err?.message || 'Login failed. Please check your credentials.');
    }
  };

  return (
    <div className="min-h-[calc(100vh-4rem)] flex items-center justify-center bg-background px-4 py-12">
      <div className="w-full max-w-md">
        <div className="bg-surface-primary rounded-xl shadow-lg p-8 border border-border">
          <div className="text-center mb-8">
            <h1 className="text-3xl font-bold text-foreground mb-2">Welcome Back</h1>
            <p className="text-muted">Sign in to your TodoGizmo account</p>
          </div>

          {error && (
            <div className="mb-4 p-3 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg">
              <p className="text-sm text-red-600 dark:text-red-400">{error}</p>
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-6">
            <div>
              <label htmlFor="email" className="block text-sm font-medium text-foreground mb-2">
                Email
              </label>
              <input
                id="email"
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
                className="w-full px-3 py-2 border border-border rounded-lg bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                placeholder="you@example.com"
              />
            </div>

            <div>
              <label htmlFor="password" className="block text-sm font-medium text-foreground mb-2">
                Password
              </label>
              <input
                id="password"
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
                className="w-full px-3 py-2 border border-border rounded-lg bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                placeholder="••••••••"
              />
            </div>

            <div className="flex items-center">
              <input
                id="rememberMe"
                type="checkbox"
                checked={rememberMe}
                onChange={(e) => setRememberMe(e.target.checked)}
                className="h-4 w-4 rounded border-border text-primary-600 focus:ring-primary-500"
              />
              <label htmlFor="rememberMe" className="ml-2 text-sm text-foreground">
                Remember me
              </label>
            </div>

            <button
              type="submit"
              disabled={isLoading}
              className="w-full py-2 px-4 bg-primary-600 hover:bg-primary-700 text-white font-medium rounded-lg shadow-sm transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isLoading ? 'Signing in...' : 'Sign In'}
            </button>
          </form>

          <div className="mt-6 text-center">
            <p className="text-sm text-muted">
              Don't have an account?{' '}
              <Link href="/register" className="text-primary-600 hover:text-primary-700 font-medium">
                Sign up
              </Link>
            </p>
          </div>
        </div>

        <div className="mt-4 text-center text-sm text-muted">
          <p>Demo accounts:</p>
          <p>guest1@example.com / Guest@123</p>
          <p>admin1@example.com / Admin@123</p>
        </div>
      </div>
    </div>
  );
}
